server:
  port: 8765


spring:
  application:
    name: api-gateway-tasks-users
  cloud:
    gateway:
      routes:
        - id: tasks-micro
          uri: http://localhost:8081/
          predicates:
            - Path=/pay/**
        - id: users-micro
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**
