server:
  port: 8765


spring:
  application:
    name: api-gateway-pay-products
  cloud:
    gateway:
      routes:
        - id: pay
          uri: http://localhost:8081/
          predicates:
            - Path=/pay/**
        - id: products
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**
