CREATE TABLE IF NOT EXISTS accounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cnum VARCHAR(8) NOT NULL,
    acid VARCHAR(20) NOT NULL,
    amount FLOAT NOT NULL,
    upd_date TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    amount INT NULL,
    price FLOAT NULL
);

