server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Tasks
          uri: http://localhost:8081/
          predicates:
            - Path=/micro-tasks/**
        - id: Users
          uri: http://localhost:8082/
          predicates:
            - Path=/micro-users/**